spring:
  datasource:
    url: jdbc:h2:file:./data;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  modulith:
    events:
      completion-mode: DELETE

automod:
  cache_size: 100

