create table AUTO_MOD_CONFIGURATION_MODERATION_RESPONSE
(
    ID               BIGINT not null primary key,
    CHANNEL_ID       BIGINT not null,
    TRUST_LEVEL      CHARACTER VARYING(20),
    TYPE             CHARACTER VARYING(10),
    TEXT             CHARACTER VARYING(255),
    DURATION         BIGINT
);
CREATE SEQUENCE AUTO_MOD_CONFIGURATION_MODERATION_RESPONSE_SEQ AS INTEGER;