name: Java Build with Gradle

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number used for build artifact
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Copy jar to root
        run: cp ./build/libs/pipbot.jar .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: pipbot_${{inputs.version}}
          path: |
            authentication_template.yml
            pipbot.jar